name: Decommission Service

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Name of the service to decommission'
        required: true
      force:
        description: 'Force execution without manual confirmation'
        required: false
        default: 'false'

jobs:
  decommission:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ github.event.inputs.service_name }}
      FORCE: ${{ github.event.inputs.force }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Validate Input
        run: |
          if [[ -z "$SERVICE_NAME" ]]; then
            echo "SERVICE_NAME is required"
            exit 1
          fi
          ./scripts/check_inventory.sh "$SERVICE_NAME"

      - name: Confirm Decommission (unless forced)
        if: ${{ env.FORCE != 'true' }}
        run: |
          echo "::notice ::Manual confirmation required."
          echo "FORCE=false. Rerun this workflow with force=true to proceed."
          exit 1

  # Kubernetes cleanup job
  k8s-cleanup:
    needs: decommission
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ github.event.inputs.service_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Drain Traffic
        run: ./scripts/drain_traffic.sh "$SERVICE_NAME"

      - name: Archive Logs
        run: ./scripts/archive_logs.sh "$SERVICE_NAME"

      - name: Snapshot DB
        run: ./scripts/snapshot_db.sh "$SERVICE_NAME"

      - name: Clean Service Registry
        run: ./scripts/remove_from_service_registry.sh "$SERVICE_NAME"

      - name: Clean DNS
        run: ./scripts/remove_dns.sh "$SERVICE_NAME"

      - name: Remove Monitoring & Alerting
        run: ./scripts/clean_monitoring.sh "$SERVICE_NAME"

  # Terraform cleanup job
  terraform-destroy:
    needs: decommission
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ github.event.inputs.service_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Destroy
        run: |
          cd infra/services/$SERVICE_NAME
          terraform init -input=false
          terraform destroy -auto-approve
