name: Fix Script Permissions

on:
  workflow_dispatch:

jobs:
  make-executable:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for git pull

      - name: Set Git Identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Add Executable Permissions
        run: |
          find scripts/ -type f -name "*.sh" -exec chmod +x {} \;
          git add scripts/
          git commit -m "Set +x permissions on all scripts" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
