name: Fix Script Permissions

on:
  workflow_dispatch:

jobs:
  make-executable:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important to fetch full history for pull

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Make all shell scripts executable
        run: |
          find scripts/ -type f -name "*.sh" -exec chmod +x {} \;
          git commit -am "Set executable permissions on scripts" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
