name: Fix Script Permissions

on:
  workflow_dispatch:

jobs:
  make-executable:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git Identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Fetch and rebase from origin
        run: |
          git fetch origin
          git rebase origin/main

      - name: Add Executable Permissions and Push
        run: |
          find scripts/ -type f -name "*.sh" -exec chmod +x {} \;
          git add scripts/
          git diff --cached --quiet || git commit -m "Set +x permissions on scripts"
          git push origin HEAD:main
