name: Fix Script Permissions

on:
  workflow_dispatch:

jobs:
  make-executable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add +x to all shell scripts
        run: |
          find scripts/ -type f -name "*.sh" -exec chmod +x {} \;
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git commit -am "Set executable permissions on scripts"
          git push
